#!/usr/bin/env python3
import modules.PySimpleGUI as sg
import random
import json
import subprocess
from dataclasses import dataclass, field
from typing import List, Tuple


@dataclass
class QuizQuestion:
    question: str
    correctAnswer: str
    wrongAnswers: List[str]
    timeout: int = field(default=10)

    def __repr__(self):
        return self.question
        
def load_quiz(filename: str) -> Tuple[List[QuizQuestion], str]:
    with open(filename, 'r') as file:
        quizDicts = json.load(file)
        questionList = []
        for q in quizDicts["listOfQuestions"]:
            qq = QuizQuestion(**q)
            questionList.append(qq)
        titleofquiz = quizDicts["title"]
    return questionList, titleofquiz

def Home_layout():
    return [
        [sg.Text('Welcome to QuizMasterMini', font=("Calibri", 24))],
        [sg.Text('_'*70)],
        [sg.Button('Make a Quiz', size = (30,2)), sg.Button('Play a Quiz', size = (30,2))],
    ]

def quiz_layout():
    return [
        [sg.Text('Select the correct answer:', size=(100, 1))],
        [sg.Text('', size=(200, 2), key='question')],
        [sg.Listbox([], bind_return_key=True, enable_events=True, size=(200, 10), key='answers', select_mode='single')],
        [sg.Button('Quit')],
        [sg.Text('', size=(30, 1), key='score')]
    ]

def main():
    home_window = sg.Window('Quiz', Home_layout(), finalize=True)

    while True:
        event, values = home_window.read()
        if event == sg.WIN_CLOSED:
            break
        if event == 'Make a Quiz':
            subprocess.Popen(["python3", "quizcreator"])
        if event == 'Play a Quiz':    
            filename = sg.popup_get_file("Please select a quiz:", initial_folder="quizzes",
                                          no_window=True, file_types=(('Quiz files', '.json'),))
            if not filename:
                continue

            questions, title = load_quiz(filename)
            question_index = 0
            score = 0
            start_quiz = False
            
            quiz_window = sg.Window('Quiz', quiz_layout(), finalize=True)

            while question_index < len(questions):
                current_question = questions[question_index]
                correct_answer = current_question.correctAnswer
                wrong_answers = current_question.wrongAnswers
                answers = random.sample([correct_answer] + wrong_answers, len(wrong_answers) + 1)

                quiz_window['question'].update(current_question.question)
                quiz_window['answers'].update(values=answers)
                quiz_window['score'].update(f'Score: {score}', visible=start_quiz)

                event, values = quiz_window.read()

                if event == sg.WIN_CLOSED or event == 'Quit':
                    quiz_window.close()
                    break

                if start_quiz:
                    if event in ('answers', 'Enter'):
                        if values['answers']:
                            if values['answers'][0] == correct_answer:
                                score += 1
                        else:
                            sg.popup('Please select an answer')
                            continue

                        question_index += 1

                    if question_index >= len(questions):
                        sg.popup(f'Quiz completed! Your score: {score}/{len(questions)}')
                        break
                else:
                    start_quiz = True

            quiz_window.close()

    home_window.close()
    
if __name__ == "__main__":
    main()

